"""Adicionar tipo de combustivel e quantidade de passageiros

Revision ID: 334928ecd2e7
Revises: 62784c72bd55
Create Date: 2025-08-12 17:45:41.727327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334928ecd2e7'
down_revision: Union[str, None] = '62784c72bd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Cria os tipos ENUM antes de usá-los
    fuel_type = sa.Enum('GASOLINA', 'ETANOL', 'FLEX', 'DIESEL', 'ELETRICO', name='fueltype')
    transmission_type = sa.Enum('AUTOMATICO', 'MANUAL', name='transmissiontype')
    
    # Etapa 1: Adicionar as novas colunas sem a restrição NOT NULL (nullable=True)
    op.add_column('cars', sa.Column('fuel_type', fuel_type, nullable=True))
    op.add_column('cars', sa.Column('transmission_type', transmission_type, nullable=True))
    op.add_column('cars', sa.Column('passengers', sa.Integer(), nullable=True))
    
    # Etapa 2: Preencher os valores nulos com valores padrão para as linhas existentes
    # Para fuel_type e transmission_type, escolha um valor padrão
    op.execute("UPDATE cars SET fuel_type = 'GASOLINA' WHERE fuel_type IS NULL")
    op.execute("UPDATE cars SET transmission_type = 'AUTOMATICO' WHERE transmission_type IS NULL")
    
    # Para passengers, escolha um valor padrão como 4
    op.execute("UPDATE cars SET passengers = 4 WHERE passengers IS NULL")
    
    # Etapa 3: Alterar as colunas para adicionar a restrição NOT NULL
    op.alter_column('cars', 'fuel_type', nullable=False)
    op.alter_column('cars', 'transmission_type', nullable=False)
    op.alter_column('cars', 'passengers', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'passengers')
    op.drop_column('cars', 'transmission_type')
    op.drop_column('cars', 'fuel_type')
    # O downgrade também deve remover os tipos ENUM para limpeza completa
    op.execute('DROP TYPE transmissiontype')
    op.execute('DROP TYPE fueltype')
    # ### end Alembic commands ###
