"""Adicionar cnh_url à tabela locacoes

Revision ID: 62784c72bd55
Revises: a0a8e0ac49dc
Create Date: 2025-08-12 10:40:51.761059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62784c72bd55'
down_revision: Union[str, None] = 'a0a8e0ac49dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locacoes', sa.Column('cnh_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locacoes', 'cnh_url')
    # ### end Alembic commands ###
