"""Adiciona cnh_photo_path à tabela locacoes

Revision ID: bf6eaf5f1062
Revises: 334928ecd2e7
Create Date: 2025-08-13 15:46:25.466041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6eaf5f1062'
down_revision: Union[str, None] = '334928ecd2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locacoes', sa.Column('cnh_photo_path', sa.String(), nullable=True))
    op.drop_column('locacoes', 'cnh_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locacoes', sa.Column('cnh_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('locacoes', 'cnh_photo_path')
    # ### end Alembic commands ###
